<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\WeCms.Shared\WeCms.Shared.csproj" />
    <ProjectReference Include="..\WeCms.Infrastructure\WeCms.Infrastructure.csproj" />
    <ProjectReference Include="..\WeCms.Persistence\WeCms.Persistence.csproj" />
    <ProjectReference Include="..\WeCms.Modules.System\WeCms.Modules.System.csproj" />
    <ProjectReference Include="..\WeCms.Modules.Cms\WeCms.Modules.Cms.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>
