-- M0-BE-006 Seed 002: Super admin user and role
-- Admin user password hash is generated by DbMigrationRunner at application startup.
-- This manual SQL seed must not insert sys_user with placeholder credentials.

-- Super admin role
INSERT IGNORE INTO `sys_role` (`code`, `name`, `description`, `is_system`, `is_builtin`, `sort_order`)
VALUES ('super_admin', '超级管理员', '系统内置超级管理员角色，拥有所有权限', 1, 1, 0);

-- Assign all permissions to super_admin role
INSERT IGNORE INTO `sys_role_permission` (`role_id`, `permission_id`)
SELECT r.id, p.id
FROM `sys_role` r, `sys_permission` p
WHERE r.code = 'super_admin' AND p.status = 1;
