using System.Text.Json.Serialization;
using WeCms.Modules.System.Auth;
using WeCms.Modules.System.Departments;
using WeCms.Modules.System.Dicts;
using WeCms.Modules.System.Files;
using WeCms.Modules.System.Logs;
using WeCms.Modules.System.Menus;
using WeCms.Modules.System.Permissions;
using WeCms.Modules.System.Posts;
using WeCms.Modules.System.Roles;
using WeCms.Modules.System.Settings;
using WeCms.Modules.System.System;
using WeCms.Modules.System.Users;
using WeCms.Shared;

namespace WeCms.Api.Json;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ApiResult<object>))]
[JsonSerializable(typeof(ApiResult<LoginResponse>))]
[JsonSerializable(typeof(ApiResult<AuthMeResponse>))]
[JsonSerializable(typeof(ApiResult<SecurePingResponse>))]
[JsonSerializable(typeof(ApiResult<SystemLiveResponse>))]
[JsonSerializable(typeof(ApiResult<SystemReadyResponse>))]
[JsonSerializable(typeof(ApiResult<SystemPingResponse>))]
[JsonSerializable(typeof(ApiResult<SystemVersionResponse>))]
[JsonSerializable(typeof(ApiResult<SystemDbCheckResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<UserSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<UserDetailDto>))]
[JsonSerializable(typeof(ApiResult<UserMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<RoleSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<RoleDetailDto>))]
[JsonSerializable(typeof(ApiResult<RoleMutationResponse>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<MenuSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<MenuTreeDto>>))]
[JsonSerializable(typeof(ApiResult<MenuDetailDto>))]
[JsonSerializable(typeof(ApiResult<MenuMutationResponse>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<PermissionSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<PermissionTreeDto>>))]
[JsonSerializable(typeof(ApiResult<PermissionDetailDto>))]
[JsonSerializable(typeof(ApiResult<PermissionMutationResponse>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<DepartmentSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<DepartmentTreeDto>>))]
[JsonSerializable(typeof(ApiResult<DepartmentDetailDto>))]
[JsonSerializable(typeof(ApiResult<DepartmentMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PostSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<PostDetailDto>))]
[JsonSerializable(typeof(ApiResult<PostMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<DictTypeSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<DictTypeDetailDto>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<DictValueDto>>))]
[JsonSerializable(typeof(ApiResult<DictMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SettingSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<SettingDetailDto>))]
[JsonSerializable(typeof(ApiResult<SettingMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<LoginLogSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<LoginLogDetailDto>))]
[JsonSerializable(typeof(ApiResult<PagedResult<AuditLogSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<AuditLogDetailDto>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SecurityEventSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<SecurityEventDetailDto>))]
[JsonSerializable(typeof(ApiResult<PagedResult<FileSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<FileDetailDto>))]
[JsonSerializable(typeof(ApiResult<FileMutationResponse>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(AuthMeResponse))]
[JsonSerializable(typeof(SecurePingResponse))]
[JsonSerializable(typeof(SystemLiveResponse))]
[JsonSerializable(typeof(SystemReadyResponse))]
[JsonSerializable(typeof(SystemPingResponse))]
[JsonSerializable(typeof(SystemVersionResponse))]
[JsonSerializable(typeof(SystemDbCheckResponse))]
[JsonSerializable(typeof(PagedResult<UserSummaryDto>))]
[JsonSerializable(typeof(UserSummaryDto))]
[JsonSerializable(typeof(UserDetailDto))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(ResetUserPasswordRequest))]
[JsonSerializable(typeof(AssignUserRolesRequest))]
[JsonSerializable(typeof(AssignUserPostsRequest))]
[JsonSerializable(typeof(UserMutationResponse))]
[JsonSerializable(typeof(PagedResult<RoleSummaryDto>))]
[JsonSerializable(typeof(RoleSummaryDto))]
[JsonSerializable(typeof(RoleDetailDto))]
[JsonSerializable(typeof(CreateRoleRequest))]
[JsonSerializable(typeof(UpdateRoleRequest))]
[JsonSerializable(typeof(AssignRolePermissionsRequest))]
[JsonSerializable(typeof(AssignRoleMenusRequest))]
[JsonSerializable(typeof(RoleMutationResponse))]
[JsonSerializable(typeof(MenuSummaryDto))]
[JsonSerializable(typeof(MenuTreeDto))]
[JsonSerializable(typeof(MenuDetailDto))]
[JsonSerializable(typeof(CreateMenuRequest))]
[JsonSerializable(typeof(UpdateMenuRequest))]
[JsonSerializable(typeof(MenuMutationResponse))]
[JsonSerializable(typeof(PermissionSummaryDto))]
[JsonSerializable(typeof(PermissionTreeDto))]
[JsonSerializable(typeof(PermissionDetailDto))]
[JsonSerializable(typeof(CreatePermissionRequest))]
[JsonSerializable(typeof(UpdatePermissionRequest))]
[JsonSerializable(typeof(PermissionMutationResponse))]
[JsonSerializable(typeof(DepartmentSummaryDto))]
[JsonSerializable(typeof(DepartmentTreeDto))]
[JsonSerializable(typeof(DepartmentDetailDto))]
[JsonSerializable(typeof(CreateDepartmentRequest))]
[JsonSerializable(typeof(UpdateDepartmentRequest))]
[JsonSerializable(typeof(DepartmentMutationResponse))]
[JsonSerializable(typeof(PagedResult<PostSummaryDto>))]
[JsonSerializable(typeof(PostSummaryDto))]
[JsonSerializable(typeof(PostDetailDto))]
[JsonSerializable(typeof(CreatePostRequest))]
[JsonSerializable(typeof(UpdatePostRequest))]
[JsonSerializable(typeof(PostMutationResponse))]
[JsonSerializable(typeof(PagedResult<DictTypeSummaryDto>))]
[JsonSerializable(typeof(DictTypeSummaryDto))]
[JsonSerializable(typeof(DictTypeDetailDto))]
[JsonSerializable(typeof(CreateDictTypeRequest))]
[JsonSerializable(typeof(UpdateDictTypeRequest))]
[JsonSerializable(typeof(DictValueDto))]
[JsonSerializable(typeof(CreateDictValueRequest))]
[JsonSerializable(typeof(UpdateDictValueRequest))]
[JsonSerializable(typeof(DictMutationResponse))]
[JsonSerializable(typeof(PagedResult<SettingSummaryDto>))]
[JsonSerializable(typeof(SettingSummaryDto))]
[JsonSerializable(typeof(SettingDetailDto))]
[JsonSerializable(typeof(UpdateSettingRequest))]
[JsonSerializable(typeof(SettingMutationResponse))]
[JsonSerializable(typeof(PagedResult<LoginLogSummaryDto>))]
[JsonSerializable(typeof(LoginLogSummaryDto))]
[JsonSerializable(typeof(LoginLogDetailDto))]
[JsonSerializable(typeof(PagedResult<AuditLogSummaryDto>))]
[JsonSerializable(typeof(AuditLogSummaryDto))]
[JsonSerializable(typeof(AuditLogDetailDto))]
[JsonSerializable(typeof(PagedResult<SecurityEventSummaryDto>))]
[JsonSerializable(typeof(SecurityEventSummaryDto))]
[JsonSerializable(typeof(SecurityEventDetailDto))]
[JsonSerializable(typeof(PagedResult<FileSummaryDto>))]
[JsonSerializable(typeof(FileSummaryDto))]
[JsonSerializable(typeof(FileDetailDto))]
[JsonSerializable(typeof(CreateFileRequest))]
[JsonSerializable(typeof(FileMutationResponse))]
[JsonSerializable(typeof(AuthUserDto))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(IReadOnlyList<UserSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<RoleSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<MenuSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<MenuTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<PermissionSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<PermissionTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<DepartmentSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<DepartmentTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<PostSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<DictTypeSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<DictValueDto>))]
[JsonSerializable(typeof(IReadOnlyList<SettingSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<LoginLogSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<AuditLogSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<SecurityEventSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<FileSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<long>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string[]>))]
[JsonSerializable(typeof(Dictionary<string, string[]>))]
public sealed partial class WeCmsJsonSerializerContext : JsonSerializerContext;
