using System.Text.Json.Serialization;
using WeCms.Modules.AccessControl.Contracts;
using WeCms.Modules.AccessControl.Records;
using WeCms.Modules.Identity.Contracts;
using WeCms.Modules.Organization.Departments;
using WeCms.Modules.Configuration.Dicts;
using WeCms.Modules.FileCenter.Files;
using WeCms.Modules.Configuration.I18n;
using WeCms.Modules.Audit.Logs;
using WeCms.Modules.Organization.Positions;
using WeCms.Modules.Security;
using WeCms.Modules.Security.Events;
using WeCms.Modules.Configuration.Settings;
using WeCms.Modules.Platform.System;
using WeCms.Shared;

namespace WeCms.Api.Json;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ApiResult<object>))]
[JsonSerializable(typeof(ApiResult<LoginResponse>))]
[JsonSerializable(typeof(ApiResult<AuthMeResponse>))]
[JsonSerializable(typeof(ApiResult<AccessProfileDto>))]
[JsonSerializable(typeof(ApiResult<AccountTwoFactorStatusResponse>))]
[JsonSerializable(typeof(ApiResult<AccountTwoFactorSetupResponse>))]
[JsonSerializable(typeof(ApiResult<AccountTwoFactorRecoveryCodesResponse>))]
[JsonSerializable(typeof(ApiResult<AccountProfileResponse>))]
[JsonSerializable(typeof(ApiResult<AccountAvatarResponse>))]
[JsonSerializable(typeof(ApiResult<AccountSecurityResponse>))]
[JsonSerializable(typeof(ApiResult<SecurePingResponse>))]
[JsonSerializable(typeof(ApiResult<SystemLiveResponse>))]
[JsonSerializable(typeof(ApiResult<SystemReadyResponse>))]
[JsonSerializable(typeof(ApiResult<SystemDependenciesResponse>))]
[JsonSerializable(typeof(ApiResult<SystemPingResponse>))]
[JsonSerializable(typeof(ApiResult<SystemVersionResponse>))]
[JsonSerializable(typeof(ApiResult<SystemDbCheckResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<UserSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<UserDetailDto>))]
[JsonSerializable(typeof(ApiResult<UserMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<RoleSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<RoleDetailDto>))]
[JsonSerializable(typeof(ApiResult<RoleMutationResponse>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<MenuSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<MenuTreeDto>>))]
[JsonSerializable(typeof(ApiResult<MenuDetailDto>))]
[JsonSerializable(typeof(ApiResult<MenuMutationResponse>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<PermissionSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<PermissionTreeDto>>))]
[JsonSerializable(typeof(ApiResult<PermissionDetailDto>))]
[JsonSerializable(typeof(ApiResult<PermissionMutationResponse>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<DepartmentSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<DepartmentTreeDto>>))]
[JsonSerializable(typeof(ApiResult<DepartmentDetailDto>))]
[JsonSerializable(typeof(ApiResult<DepartmentMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PositionSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<PositionDetailDto>))]
[JsonSerializable(typeof(ApiResult<PositionMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<DictTypeSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<DictTypeDetailDto>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<DictValueDto>>))]
[JsonSerializable(typeof(ApiResult<DictMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SettingSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<SettingDetailDto>))]
[JsonSerializable(typeof(ApiResult<SettingMutationResponse>))]
[JsonSerializable(typeof(ApiResult<ValidateIpRulesResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<I18nMessageSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<I18nMessageDetailDto>))]
[JsonSerializable(typeof(ApiResult<I18nMessagesResponse>))]
[JsonSerializable(typeof(ApiResult<AccountI18nSwitchResponse>))]
[JsonSerializable(typeof(ApiResult<I18nMutationResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<LoginLogSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<LoginLogDetailDto>))]
[JsonSerializable(typeof(ApiResult<PagedResult<AuditLogSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<AuditLogDetailDto>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SecurityEventSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<SecurityEventDetailDto>))]
[JsonSerializable(typeof(ApiResult<SecurityStatusDto>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SecurityBanSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<SecurityBanDetailDto>))]
[JsonSerializable(typeof(ApiResult<SecurityBanMutationResponse>))]
[JsonSerializable(typeof(ApiResult<BatchUnbanSecurityBansResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<FileSummaryDto>>))]
[JsonSerializable(typeof(ApiResult<FileDetailDto>))]
[JsonSerializable(typeof(ApiResult<FileMutationResponse>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(TwoFactorVerifyRequest))]
[JsonSerializable(typeof(TwoFactorRecoveryCodeRequest))]
[JsonSerializable(typeof(AccountTwoFactorConfirmRequest))]
[JsonSerializable(typeof(AccountTwoFactorDisableRequest))]
[JsonSerializable(typeof(AccountTwoFactorRegenerateRecoveryCodesRequest))]
[JsonSerializable(typeof(UpdateAccountProfileRequest))]
[JsonSerializable(typeof(ChangeAccountPasswordRequest))]
[JsonSerializable(typeof(AccountAvatarUploadRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(AuthMeResponse))]
[JsonSerializable(typeof(AccessProfileDto))]
[JsonSerializable(typeof(AccountTwoFactorStatusResponse))]
[JsonSerializable(typeof(AccountTwoFactorSetupResponse))]
[JsonSerializable(typeof(AccountTwoFactorRecoveryCodesResponse))]
[JsonSerializable(typeof(AccountProfileResponse))]
[JsonSerializable(typeof(AccountAvatarResponse))]
[JsonSerializable(typeof(AccountSecurityResponse))]
[JsonSerializable(typeof(SecurePingResponse))]
[JsonSerializable(typeof(SystemLiveResponse))]
[JsonSerializable(typeof(SystemReadyResponse))]
[JsonSerializable(typeof(SystemDependencyStatus))]
[JsonSerializable(typeof(SystemDependenciesResponse))]
[JsonSerializable(typeof(SystemPingResponse))]
[JsonSerializable(typeof(SystemVersionResponse))]
[JsonSerializable(typeof(SystemDbCheckResponse))]
[JsonSerializable(typeof(PagedResult<UserSummaryDto>))]
[JsonSerializable(typeof(UserSummaryDto))]
[JsonSerializable(typeof(UserDetailDto))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(ResetUserPasswordRequest))]
[JsonSerializable(typeof(ResetUserTwoFactorRequest))]
[JsonSerializable(typeof(AssignUserRolesRequest))]
[JsonSerializable(typeof(AssignUserPositionsRequest))]
[JsonSerializable(typeof(UserMutationResponse))]
[JsonSerializable(typeof(PagedResult<RoleSummaryDto>))]
[JsonSerializable(typeof(RoleSummaryDto))]
[JsonSerializable(typeof(RoleDetailDto))]
[JsonSerializable(typeof(CreateRoleRequest))]
[JsonSerializable(typeof(UpdateRoleRequest))]
[JsonSerializable(typeof(AssignRolePermissionsRequest))]
[JsonSerializable(typeof(AssignRoleMenusRequest))]
[JsonSerializable(typeof(RoleMutationResponse))]
[JsonSerializable(typeof(MenuSummaryDto))]
[JsonSerializable(typeof(MenuTreeDto))]
[JsonSerializable(typeof(MenuDetailDto))]
[JsonSerializable(typeof(CreateMenuRequest))]
[JsonSerializable(typeof(UpdateMenuRequest))]
[JsonSerializable(typeof(SortMenusRequest))]
[JsonSerializable(typeof(SortMenuItemRequest))]
[JsonSerializable(typeof(MenuMutationResponse))]
[JsonSerializable(typeof(PermissionSummaryDto))]
[JsonSerializable(typeof(PermissionTreeDto))]
[JsonSerializable(typeof(PermissionDetailDto))]
[JsonSerializable(typeof(CreatePermissionRequest))]
[JsonSerializable(typeof(UpdatePermissionRequest))]
[JsonSerializable(typeof(PermissionMutationResponse))]
[JsonSerializable(typeof(DepartmentSummaryDto))]
[JsonSerializable(typeof(DepartmentTreeDto))]
[JsonSerializable(typeof(DepartmentDetailDto))]
[JsonSerializable(typeof(CreateDepartmentRequest))]
[JsonSerializable(typeof(UpdateDepartmentRequest))]
[JsonSerializable(typeof(DepartmentMutationResponse))]
[JsonSerializable(typeof(PagedResult<PositionSummaryDto>))]
[JsonSerializable(typeof(PositionSummaryDto))]
[JsonSerializable(typeof(PositionDetailDto))]
[JsonSerializable(typeof(CreatePositionRequest))]
[JsonSerializable(typeof(UpdatePositionRequest))]
[JsonSerializable(typeof(PositionMutationResponse))]
[JsonSerializable(typeof(PagedResult<DictTypeSummaryDto>))]
[JsonSerializable(typeof(DictTypeSummaryDto))]
[JsonSerializable(typeof(DictTypeDetailDto))]
[JsonSerializable(typeof(CreateDictTypeRequest))]
[JsonSerializable(typeof(UpdateDictTypeRequest))]
[JsonSerializable(typeof(DisableDictTypeRequest))]
[JsonSerializable(typeof(DictValueDto))]
[JsonSerializable(typeof(CreateDictValueRequest))]
[JsonSerializable(typeof(UpdateDictValueRequest))]
[JsonSerializable(typeof(DictMutationResponse))]
[JsonSerializable(typeof(PagedResult<SettingSummaryDto>))]
[JsonSerializable(typeof(SettingSummaryDto))]
[JsonSerializable(typeof(SettingDetailDto))]
[JsonSerializable(typeof(UpdateSettingRequest))]
[JsonSerializable(typeof(ValidateIpRulesRequest))]
[JsonSerializable(typeof(ValidateIpRulesResponse))]
[JsonSerializable(typeof(SettingMutationResponse))]
[JsonSerializable(typeof(PagedResult<I18nMessageSummaryDto>))]
[JsonSerializable(typeof(I18nMessageSummaryDto))]
[JsonSerializable(typeof(I18nMessageDetailDto))]
[JsonSerializable(typeof(CreateI18nMessageRequest))]
[JsonSerializable(typeof(UpdateI18nMessageRequest))]
[JsonSerializable(typeof(SwitchAccountLocaleRequest))]
[JsonSerializable(typeof(I18nMessagesResponse))]
[JsonSerializable(typeof(AccountI18nSwitchResponse))]
[JsonSerializable(typeof(I18nMutationResponse))]
[JsonSerializable(typeof(PagedResult<LoginLogSummaryDto>))]
[JsonSerializable(typeof(LoginLogSummaryDto))]
[JsonSerializable(typeof(LoginLogDetailDto))]
[JsonSerializable(typeof(PagedResult<AuditLogSummaryDto>))]
[JsonSerializable(typeof(AuditLogSummaryDto))]
[JsonSerializable(typeof(AuditLogDetailDto))]
[JsonSerializable(typeof(PagedResult<SecurityEventSummaryDto>))]
[JsonSerializable(typeof(SecurityEventSummaryDto))]
[JsonSerializable(typeof(SecurityEventDetailDto))]
[JsonSerializable(typeof(SecurityStatusDto))]
[JsonSerializable(typeof(PagedResult<SecurityBanSummaryDto>))]
[JsonSerializable(typeof(SecurityBanSummaryDto))]
[JsonSerializable(typeof(SecurityBanDetailDto))]
[JsonSerializable(typeof(UnbanSecurityBanRequest))]
[JsonSerializable(typeof(BatchUnbanSecurityBansRequest))]
[JsonSerializable(typeof(SecurityBanMutationResponse))]
[JsonSerializable(typeof(BatchUnbanSecurityBansResponse))]
[JsonSerializable(typeof(PagedResult<FileSummaryDto>))]
[JsonSerializable(typeof(FileSummaryDto))]
[JsonSerializable(typeof(FileDetailDto))]
[JsonSerializable(typeof(CreateFileRequest))]
[JsonSerializable(typeof(FileMutationResponse))]
[JsonSerializable(typeof(AuthUserDto))]
[JsonSerializable(typeof(AuthMenuTreeDto))]
[JsonSerializable(typeof(IReadOnlyList<AuthMenuTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(IReadOnlyList<UserSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<RoleSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<MenuSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<MenuTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<PermissionSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<PermissionTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<DepartmentSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<DepartmentTreeDto>))]
[JsonSerializable(typeof(IReadOnlyList<PositionSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<DictTypeSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<DictValueDto>))]
[JsonSerializable(typeof(IReadOnlyList<SettingSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<I18nMessageSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<LoginLogSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<AuditLogSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<SecurityEventSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<SecurityBanSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<FileSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<long>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string[]>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, string[]>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
public sealed partial class WeCmsJsonSerializerContext : JsonSerializerContext;
