using System.Text.Json.Serialization;
using WeCms.Modules.System.Auth;
using WeCms.Modules.System.Auth.TwoFactor;
using WeCms.Modules.System.Users;
using WeCms.Modules.System.Roles;
using WeCms.Modules.System.Menus;
using WeCms.Modules.System.Settings;
using WeCms.Modules.System.Dicts;
using WeCms.Modules.System.Files;
using WeCms.Modules.System.Logs;
using WeCms.Modules.System.Permissions;
using WeCms.Modules.System.I18n;
using WeCms.Modules.System.Security;
using WeCms.Shared;

namespace WeCms.Api.Json;

[JsonSerializable(typeof(ApiResult<string>))]
[JsonSerializable(typeof(ApiResult<object>))]
[JsonSerializable(typeof(ApiResult<int>))]
[JsonSerializable(typeof(ApiResult<LoginResponse>))]
[JsonSerializable(typeof(ApiResult<RefreshResponse>))]
[JsonSerializable(typeof(ApiResult<CurrentUserResponse>))]
[JsonSerializable(typeof(ApiResult<TwoFactorSetupResponse>))]
[JsonSerializable(typeof(ApiResult<PagedResult<UserListItem>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<RoleListItem>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<FileItem>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<LoginLogItem>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<AuditLogItem>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SecurityEventItem>>))]
[JsonSerializable(typeof(ApiResult<UserDetail>))]
[JsonSerializable(typeof(ApiResult<RoleDetail>))]
[JsonSerializable(typeof(ApiResult<MenuDetail>))]
[JsonSerializable(typeof(ApiResult<List<MenuTreeItem>>))]
[JsonSerializable(typeof(ApiResult<List<SettingItem>>))]
[JsonSerializable(typeof(ApiResult<List<DictTypeItem>>))]
[JsonSerializable(typeof(ApiResult<List<DictValueItem>>))]
[JsonSerializable(typeof(ApiResult<UploadResult>))]
[JsonSerializable(typeof(ApiResult<List<I18nMessageItem>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<PermissionItem>>))]
[JsonSerializable(typeof(ApiResult<IReadOnlyList<SessionItem>>))]
[JsonSerializable(typeof(ApiResult<PongResponse>))]
[JsonSerializable(typeof(ApiResult<VersionResponse>))]
[JsonSerializable(typeof(ApiResult<DbCheckResponse>))]
[JsonSerializable(typeof(ApiResult<IdResponse>))]
[JsonSerializable(typeof(ApiResult<SyncResultResponse>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(RefreshRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(RefreshResponse))]
[JsonSerializable(typeof(CurrentUserResponse))]
[JsonSerializable(typeof(TwoFactorSetupResponse))]
[JsonSerializable(typeof(TwoFactorEnableRequest))]
[JsonSerializable(typeof(TwoFactorDisableRequest))]
[JsonSerializable(typeof(TwoFactorVerifyRequest))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(UserListItem))]
[JsonSerializable(typeof(UserDetail))]
[JsonSerializable(typeof(PagedResult<UserListItem>))]
[JsonSerializable(typeof(PagedResult<RoleListItem>))]
[JsonSerializable(typeof(PagedResult<FileItem>))]
[JsonSerializable(typeof(PagedResult<LoginLogItem>))]
[JsonSerializable(typeof(PagedResult<AuditLogItem>))]
[JsonSerializable(typeof(PagedResult<SecurityEventItem>))]
[JsonSerializable(typeof(RoleListItem))]
[JsonSerializable(typeof(FileItem))]
[JsonSerializable(typeof(LoginLogItem))]
[JsonSerializable(typeof(AuditLogItem))]
[JsonSerializable(typeof(SecurityEventItem))]
[JsonSerializable(typeof(CreateRoleRequest))]
[JsonSerializable(typeof(UpdateRoleRequest))]
[JsonSerializable(typeof(AssignMenusRequest))]
[JsonSerializable(typeof(AssignPermissionsRequest))]
[JsonSerializable(typeof(RoleDetail))]
[JsonSerializable(typeof(CreateMenuRequest))]
[JsonSerializable(typeof(UpdateMenuRequest))]
[JsonSerializable(typeof(MenuSortRequest))]
[JsonSerializable(typeof(MenuTreeItem))]
[JsonSerializable(typeof(MenuDetail))]
[JsonSerializable(typeof(UpdateSettingRequest))]
[JsonSerializable(typeof(SettingItem))]
[JsonSerializable(typeof(CreateDictTypeRequest))]
[JsonSerializable(typeof(CreateDictValueRequest))]
[JsonSerializable(typeof(DictTypeItem))]
[JsonSerializable(typeof(DictValueItem))]
[JsonSerializable(typeof(UploadResult))]
[JsonSerializable(typeof(CreateI18nRequest))]
[JsonSerializable(typeof(UpdateI18nRequest))]
[JsonSerializable(typeof(I18nMessageItem))]
[JsonSerializable(typeof(PermissionItem))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(ForgotPasswordRequest))]
[JsonSerializable(typeof(ResetPasswordRequest))]
[JsonSerializable(typeof(SessionItem))]
[JsonSerializable(typeof(PongResponse))]
[JsonSerializable(typeof(VersionResponse))]
[JsonSerializable(typeof(DbCheckResponse))]
[JsonSerializable(typeof(HealthReadyResponse))]
[JsonSerializable(typeof(ApiResult<HealthReadyResponse>))]
[JsonSerializable(typeof(HealthLiveResponse))]
[JsonSerializable(typeof(ApiResult<HealthLiveResponse>))]
[JsonSerializable(typeof(IdResponse))]
[JsonSerializable(typeof(SyncResultResponse))]
internal partial class WeCmsJsonContext : JsonSerializerContext
{
}
