CREATE TABLE sys_audit_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NULL,
  username VARCHAR(64) NULL,
  module VARCHAR(80) NOT NULL,
  resource VARCHAR(80) NOT NULL,
  action VARCHAR(80) NOT NULL,
  target_id VARCHAR(128) NULL,
  request_method VARCHAR(16) NOT NULL,
  request_path VARCHAR(160) NOT NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  trace_id VARCHAR(64) NULL,
  result VARCHAR(32) NOT NULL,
  detail VARCHAR(500) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  KEY ix_sys_audit_log_user_id (user_id),
  KEY ix_sys_audit_log_created_at (created_at),
  KEY ix_sys_audit_log_module_resource_action (module, resource, action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
