<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WeCms.Api\WeCms.Api.csproj" />
    <ProjectReference Include="..\..\src\WeCms.EventBus.SqlSugar\WeCms.EventBus.SqlSugar.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Modules.AccessControl.SqlSugar\WeCms.Modules.AccessControl.SqlSugar.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Modules.Identity\WeCms.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Modules.Identity.SqlSugar\WeCms.Modules.Identity.SqlSugar.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Modules.Platform.SqlSugar\WeCms.Modules.Platform.SqlSugar.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Infrastructure\WeCms.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
