<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\WeCms.Api\WeCms.Api.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Persistence\WeCms.Persistence.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Modules.System\WeCms.Modules.System.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Infrastructure\WeCms.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\WeCms.Shared\WeCms.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
