<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WeCms.Shared\WeCms.Shared.csproj" />
    <ProjectReference Include="..\WeCms.Modules.System\WeCms.Modules.System.csproj" />
    <ProjectReference Include="..\WeCms.Modules.Cms\WeCms.Modules.Cms.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL3050;IL2070;IL2072</WarningsAsErrors>
  </PropertyGroup>

</Project>
